//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateAuthorityConfigInitParameters) DeepCopyInto(out *CertificateAuthorityConfigInitParameters) {
	*out = *in
	if in.ConfigType != nil {
		in, out := &in.ConfigType, &out.ConfigType
		*out = new(string)
		**out = **in
	}
	if in.IssuerCertificateAuthorityID != nil {
		in, out := &in.IssuerCertificateAuthorityID, &out.IssuerCertificateAuthorityID
		*out = new(string)
		**out = **in
	}
	if in.SigningAlgorithm != nil {
		in, out := &in.SigningAlgorithm, &out.SigningAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = make([]SubjectInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Validity != nil {
		in, out := &in.Validity, &out.Validity
		*out = make([]ValidityInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VersionName != nil {
		in, out := &in.VersionName, &out.VersionName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateAuthorityConfigInitParameters.
func (in *CertificateAuthorityConfigInitParameters) DeepCopy() *CertificateAuthorityConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(CertificateAuthorityConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateAuthorityConfigObservation) DeepCopyInto(out *CertificateAuthorityConfigObservation) {
	*out = *in
	if in.ConfigType != nil {
		in, out := &in.ConfigType, &out.ConfigType
		*out = new(string)
		**out = **in
	}
	if in.IssuerCertificateAuthorityID != nil {
		in, out := &in.IssuerCertificateAuthorityID, &out.IssuerCertificateAuthorityID
		*out = new(string)
		**out = **in
	}
	if in.SigningAlgorithm != nil {
		in, out := &in.SigningAlgorithm, &out.SigningAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = make([]SubjectObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Validity != nil {
		in, out := &in.Validity, &out.Validity
		*out = make([]ValidityObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VersionName != nil {
		in, out := &in.VersionName, &out.VersionName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateAuthorityConfigObservation.
func (in *CertificateAuthorityConfigObservation) DeepCopy() *CertificateAuthorityConfigObservation {
	if in == nil {
		return nil
	}
	out := new(CertificateAuthorityConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateAuthorityConfigParameters) DeepCopyInto(out *CertificateAuthorityConfigParameters) {
	*out = *in
	if in.ConfigType != nil {
		in, out := &in.ConfigType, &out.ConfigType
		*out = new(string)
		**out = **in
	}
	if in.IssuerCertificateAuthorityID != nil {
		in, out := &in.IssuerCertificateAuthorityID, &out.IssuerCertificateAuthorityID
		*out = new(string)
		**out = **in
	}
	if in.SigningAlgorithm != nil {
		in, out := &in.SigningAlgorithm, &out.SigningAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = make([]SubjectParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Validity != nil {
		in, out := &in.Validity, &out.Validity
		*out = make([]ValidityParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VersionName != nil {
		in, out := &in.VersionName, &out.VersionName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateAuthorityConfigParameters.
func (in *CertificateAuthorityConfigParameters) DeepCopy() *CertificateAuthorityConfigParameters {
	if in == nil {
		return nil
	}
	out := new(CertificateAuthorityConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateAuthorityRulesInitParameters) DeepCopyInto(out *CertificateAuthorityRulesInitParameters) {
	*out = *in
	if in.CertificateAuthorityMaxValidityDuration != nil {
		in, out := &in.CertificateAuthorityMaxValidityDuration, &out.CertificateAuthorityMaxValidityDuration
		*out = new(string)
		**out = **in
	}
	if in.LeafCertificateMaxValidityDuration != nil {
		in, out := &in.LeafCertificateMaxValidityDuration, &out.LeafCertificateMaxValidityDuration
		*out = new(string)
		**out = **in
	}
	if in.RuleType != nil {
		in, out := &in.RuleType, &out.RuleType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateAuthorityRulesInitParameters.
func (in *CertificateAuthorityRulesInitParameters) DeepCopy() *CertificateAuthorityRulesInitParameters {
	if in == nil {
		return nil
	}
	out := new(CertificateAuthorityRulesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateAuthorityRulesObservation) DeepCopyInto(out *CertificateAuthorityRulesObservation) {
	*out = *in
	if in.CertificateAuthorityMaxValidityDuration != nil {
		in, out := &in.CertificateAuthorityMaxValidityDuration, &out.CertificateAuthorityMaxValidityDuration
		*out = new(string)
		**out = **in
	}
	if in.LeafCertificateMaxValidityDuration != nil {
		in, out := &in.LeafCertificateMaxValidityDuration, &out.LeafCertificateMaxValidityDuration
		*out = new(string)
		**out = **in
	}
	if in.RuleType != nil {
		in, out := &in.RuleType, &out.RuleType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateAuthorityRulesObservation.
func (in *CertificateAuthorityRulesObservation) DeepCopy() *CertificateAuthorityRulesObservation {
	if in == nil {
		return nil
	}
	out := new(CertificateAuthorityRulesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateAuthorityRulesParameters) DeepCopyInto(out *CertificateAuthorityRulesParameters) {
	*out = *in
	if in.CertificateAuthorityMaxValidityDuration != nil {
		in, out := &in.CertificateAuthorityMaxValidityDuration, &out.CertificateAuthorityMaxValidityDuration
		*out = new(string)
		**out = **in
	}
	if in.LeafCertificateMaxValidityDuration != nil {
		in, out := &in.LeafCertificateMaxValidityDuration, &out.LeafCertificateMaxValidityDuration
		*out = new(string)
		**out = **in
	}
	if in.RuleType != nil {
		in, out := &in.RuleType, &out.RuleType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateAuthorityRulesParameters.
func (in *CertificateAuthorityRulesParameters) DeepCopy() *CertificateAuthorityRulesParameters {
	if in == nil {
		return nil
	}
	out := new(CertificateAuthorityRulesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateRevocationListDetailsInitParameters) DeepCopyInto(out *CertificateRevocationListDetailsInitParameters) {
	*out = *in
	if in.CustomFormattedUrls != nil {
		in, out := &in.CustomFormattedUrls, &out.CustomFormattedUrls
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ObjectStorageConfig != nil {
		in, out := &in.ObjectStorageConfig, &out.ObjectStorageConfig
		*out = make([]ObjectStorageConfigInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateRevocationListDetailsInitParameters.
func (in *CertificateRevocationListDetailsInitParameters) DeepCopy() *CertificateRevocationListDetailsInitParameters {
	if in == nil {
		return nil
	}
	out := new(CertificateRevocationListDetailsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateRevocationListDetailsObservation) DeepCopyInto(out *CertificateRevocationListDetailsObservation) {
	*out = *in
	if in.CustomFormattedUrls != nil {
		in, out := &in.CustomFormattedUrls, &out.CustomFormattedUrls
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ObjectStorageConfig != nil {
		in, out := &in.ObjectStorageConfig, &out.ObjectStorageConfig
		*out = make([]ObjectStorageConfigObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateRevocationListDetailsObservation.
func (in *CertificateRevocationListDetailsObservation) DeepCopy() *CertificateRevocationListDetailsObservation {
	if in == nil {
		return nil
	}
	out := new(CertificateRevocationListDetailsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateRevocationListDetailsParameters) DeepCopyInto(out *CertificateRevocationListDetailsParameters) {
	*out = *in
	if in.CustomFormattedUrls != nil {
		in, out := &in.CustomFormattedUrls, &out.CustomFormattedUrls
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ObjectStorageConfig != nil {
		in, out := &in.ObjectStorageConfig, &out.ObjectStorageConfig
		*out = make([]ObjectStorageConfigParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateRevocationListDetailsParameters.
func (in *CertificateRevocationListDetailsParameters) DeepCopy() *CertificateRevocationListDetailsParameters {
	if in == nil {
		return nil
	}
	out := new(CertificateRevocationListDetailsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CurrentVersionInitParameters) DeepCopyInto(out *CurrentVersionInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CurrentVersionInitParameters.
func (in *CurrentVersionInitParameters) DeepCopy() *CurrentVersionInitParameters {
	if in == nil {
		return nil
	}
	out := new(CurrentVersionInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CurrentVersionObservation) DeepCopyInto(out *CurrentVersionObservation) {
	*out = *in
	if in.CertificateAuthorityID != nil {
		in, out := &in.CertificateAuthorityID, &out.CertificateAuthorityID
		*out = new(string)
		**out = **in
	}
	if in.IssuerCAVersionNumber != nil {
		in, out := &in.IssuerCAVersionNumber, &out.IssuerCAVersionNumber
		*out = new(string)
		**out = **in
	}
	if in.RevocationStatus != nil {
		in, out := &in.RevocationStatus, &out.RevocationStatus
		*out = make([]RevocationStatusObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SerialNumber != nil {
		in, out := &in.SerialNumber, &out.SerialNumber
		*out = new(string)
		**out = **in
	}
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TimeCreated != nil {
		in, out := &in.TimeCreated, &out.TimeCreated
		*out = new(string)
		**out = **in
	}
	if in.TimeOfDeletion != nil {
		in, out := &in.TimeOfDeletion, &out.TimeOfDeletion
		*out = new(string)
		**out = **in
	}
	if in.Validity != nil {
		in, out := &in.Validity, &out.Validity
		*out = make([]CurrentVersionValidityObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VersionName != nil {
		in, out := &in.VersionName, &out.VersionName
		*out = new(string)
		**out = **in
	}
	if in.VersionNumber != nil {
		in, out := &in.VersionNumber, &out.VersionNumber
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CurrentVersionObservation.
func (in *CurrentVersionObservation) DeepCopy() *CurrentVersionObservation {
	if in == nil {
		return nil
	}
	out := new(CurrentVersionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CurrentVersionParameters) DeepCopyInto(out *CurrentVersionParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CurrentVersionParameters.
func (in *CurrentVersionParameters) DeepCopy() *CurrentVersionParameters {
	if in == nil {
		return nil
	}
	out := new(CurrentVersionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CurrentVersionValidityInitParameters) DeepCopyInto(out *CurrentVersionValidityInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CurrentVersionValidityInitParameters.
func (in *CurrentVersionValidityInitParameters) DeepCopy() *CurrentVersionValidityInitParameters {
	if in == nil {
		return nil
	}
	out := new(CurrentVersionValidityInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CurrentVersionValidityObservation) DeepCopyInto(out *CurrentVersionValidityObservation) {
	*out = *in
	if in.TimeOfValidityNotAfter != nil {
		in, out := &in.TimeOfValidityNotAfter, &out.TimeOfValidityNotAfter
		*out = new(string)
		**out = **in
	}
	if in.TimeOfValidityNotBefore != nil {
		in, out := &in.TimeOfValidityNotBefore, &out.TimeOfValidityNotBefore
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CurrentVersionValidityObservation.
func (in *CurrentVersionValidityObservation) DeepCopy() *CurrentVersionValidityObservation {
	if in == nil {
		return nil
	}
	out := new(CurrentVersionValidityObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CurrentVersionValidityParameters) DeepCopyInto(out *CurrentVersionValidityParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CurrentVersionValidityParameters.
func (in *CurrentVersionValidityParameters) DeepCopy() *CurrentVersionValidityParameters {
	if in == nil {
		return nil
	}
	out := new(CurrentVersionValidityParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementCertificateAuthority) DeepCopyInto(out *ManagementCertificateAuthority) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementCertificateAuthority.
func (in *ManagementCertificateAuthority) DeepCopy() *ManagementCertificateAuthority {
	if in == nil {
		return nil
	}
	out := new(ManagementCertificateAuthority)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagementCertificateAuthority) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementCertificateAuthorityInitParameters) DeepCopyInto(out *ManagementCertificateAuthorityInitParameters) {
	*out = *in
	if in.CertificateAuthorityConfig != nil {
		in, out := &in.CertificateAuthorityConfig, &out.CertificateAuthorityConfig
		*out = make([]CertificateAuthorityConfigInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CertificateAuthorityRules != nil {
		in, out := &in.CertificateAuthorityRules, &out.CertificateAuthorityRules
		*out = make([]CertificateAuthorityRulesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CertificateRevocationListDetails != nil {
		in, out := &in.CertificateRevocationListDetails, &out.CertificateRevocationListDetails
		*out = make([]CertificateRevocationListDetailsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.KMSKeyID != nil {
		in, out := &in.KMSKeyID, &out.KMSKeyID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementCertificateAuthorityInitParameters.
func (in *ManagementCertificateAuthorityInitParameters) DeepCopy() *ManagementCertificateAuthorityInitParameters {
	if in == nil {
		return nil
	}
	out := new(ManagementCertificateAuthorityInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementCertificateAuthorityList) DeepCopyInto(out *ManagementCertificateAuthorityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagementCertificateAuthority, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementCertificateAuthorityList.
func (in *ManagementCertificateAuthorityList) DeepCopy() *ManagementCertificateAuthorityList {
	if in == nil {
		return nil
	}
	out := new(ManagementCertificateAuthorityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagementCertificateAuthorityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementCertificateAuthorityObservation) DeepCopyInto(out *ManagementCertificateAuthorityObservation) {
	*out = *in
	if in.CertificateAuthorityConfig != nil {
		in, out := &in.CertificateAuthorityConfig, &out.CertificateAuthorityConfig
		*out = make([]CertificateAuthorityConfigObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CertificateAuthorityRules != nil {
		in, out := &in.CertificateAuthorityRules, &out.CertificateAuthorityRules
		*out = make([]CertificateAuthorityRulesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CertificateRevocationListDetails != nil {
		in, out := &in.CertificateRevocationListDetails, &out.CertificateRevocationListDetails
		*out = make([]CertificateRevocationListDetailsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.ConfigType != nil {
		in, out := &in.ConfigType, &out.ConfigType
		*out = new(string)
		**out = **in
	}
	if in.CurrentVersion != nil {
		in, out := &in.CurrentVersion, &out.CurrentVersion
		*out = make([]CurrentVersionObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IssuerCertificateAuthorityID != nil {
		in, out := &in.IssuerCertificateAuthorityID, &out.IssuerCertificateAuthorityID
		*out = new(string)
		**out = **in
	}
	if in.KMSKeyID != nil {
		in, out := &in.KMSKeyID, &out.KMSKeyID
		*out = new(string)
		**out = **in
	}
	if in.LifecycleDetails != nil {
		in, out := &in.LifecycleDetails, &out.LifecycleDetails
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.SigningAlgorithm != nil {
		in, out := &in.SigningAlgorithm, &out.SigningAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = make([]ManagementCertificateAuthoritySubjectObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TimeCreated != nil {
		in, out := &in.TimeCreated, &out.TimeCreated
		*out = new(string)
		**out = **in
	}
	if in.TimeOfDeletion != nil {
		in, out := &in.TimeOfDeletion, &out.TimeOfDeletion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementCertificateAuthorityObservation.
func (in *ManagementCertificateAuthorityObservation) DeepCopy() *ManagementCertificateAuthorityObservation {
	if in == nil {
		return nil
	}
	out := new(ManagementCertificateAuthorityObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementCertificateAuthorityParameters) DeepCopyInto(out *ManagementCertificateAuthorityParameters) {
	*out = *in
	if in.CertificateAuthorityConfig != nil {
		in, out := &in.CertificateAuthorityConfig, &out.CertificateAuthorityConfig
		*out = make([]CertificateAuthorityConfigParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CertificateAuthorityRules != nil {
		in, out := &in.CertificateAuthorityRules, &out.CertificateAuthorityRules
		*out = make([]CertificateAuthorityRulesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CertificateRevocationListDetails != nil {
		in, out := &in.CertificateRevocationListDetails, &out.CertificateRevocationListDetails
		*out = make([]CertificateRevocationListDetailsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.KMSKeyID != nil {
		in, out := &in.KMSKeyID, &out.KMSKeyID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementCertificateAuthorityParameters.
func (in *ManagementCertificateAuthorityParameters) DeepCopy() *ManagementCertificateAuthorityParameters {
	if in == nil {
		return nil
	}
	out := new(ManagementCertificateAuthorityParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementCertificateAuthoritySpec) DeepCopyInto(out *ManagementCertificateAuthoritySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementCertificateAuthoritySpec.
func (in *ManagementCertificateAuthoritySpec) DeepCopy() *ManagementCertificateAuthoritySpec {
	if in == nil {
		return nil
	}
	out := new(ManagementCertificateAuthoritySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementCertificateAuthorityStatus) DeepCopyInto(out *ManagementCertificateAuthorityStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementCertificateAuthorityStatus.
func (in *ManagementCertificateAuthorityStatus) DeepCopy() *ManagementCertificateAuthorityStatus {
	if in == nil {
		return nil
	}
	out := new(ManagementCertificateAuthorityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementCertificateAuthoritySubjectInitParameters) DeepCopyInto(out *ManagementCertificateAuthoritySubjectInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementCertificateAuthoritySubjectInitParameters.
func (in *ManagementCertificateAuthoritySubjectInitParameters) DeepCopy() *ManagementCertificateAuthoritySubjectInitParameters {
	if in == nil {
		return nil
	}
	out := new(ManagementCertificateAuthoritySubjectInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementCertificateAuthoritySubjectObservation) DeepCopyInto(out *ManagementCertificateAuthoritySubjectObservation) {
	*out = *in
	if in.CommonName != nil {
		in, out := &in.CommonName, &out.CommonName
		*out = new(string)
		**out = **in
	}
	if in.Country != nil {
		in, out := &in.Country, &out.Country
		*out = new(string)
		**out = **in
	}
	if in.DistinguishedNameQualifier != nil {
		in, out := &in.DistinguishedNameQualifier, &out.DistinguishedNameQualifier
		*out = new(string)
		**out = **in
	}
	if in.DomainComponent != nil {
		in, out := &in.DomainComponent, &out.DomainComponent
		*out = new(string)
		**out = **in
	}
	if in.GenerationQualifier != nil {
		in, out := &in.GenerationQualifier, &out.GenerationQualifier
		*out = new(string)
		**out = **in
	}
	if in.GivenName != nil {
		in, out := &in.GivenName, &out.GivenName
		*out = new(string)
		**out = **in
	}
	if in.Initials != nil {
		in, out := &in.Initials, &out.Initials
		*out = new(string)
		**out = **in
	}
	if in.LocalityName != nil {
		in, out := &in.LocalityName, &out.LocalityName
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.OrganizationalUnit != nil {
		in, out := &in.OrganizationalUnit, &out.OrganizationalUnit
		*out = new(string)
		**out = **in
	}
	if in.Pseudonym != nil {
		in, out := &in.Pseudonym, &out.Pseudonym
		*out = new(string)
		**out = **in
	}
	if in.SerialNumber != nil {
		in, out := &in.SerialNumber, &out.SerialNumber
		*out = new(string)
		**out = **in
	}
	if in.StateOrProvinceName != nil {
		in, out := &in.StateOrProvinceName, &out.StateOrProvinceName
		*out = new(string)
		**out = **in
	}
	if in.Street != nil {
		in, out := &in.Street, &out.Street
		*out = new(string)
		**out = **in
	}
	if in.Surname != nil {
		in, out := &in.Surname, &out.Surname
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementCertificateAuthoritySubjectObservation.
func (in *ManagementCertificateAuthoritySubjectObservation) DeepCopy() *ManagementCertificateAuthoritySubjectObservation {
	if in == nil {
		return nil
	}
	out := new(ManagementCertificateAuthoritySubjectObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementCertificateAuthoritySubjectParameters) DeepCopyInto(out *ManagementCertificateAuthoritySubjectParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementCertificateAuthoritySubjectParameters.
func (in *ManagementCertificateAuthoritySubjectParameters) DeepCopy() *ManagementCertificateAuthoritySubjectParameters {
	if in == nil {
		return nil
	}
	out := new(ManagementCertificateAuthoritySubjectParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageConfigInitParameters) DeepCopyInto(out *ObjectStorageConfigInitParameters) {
	*out = *in
	if in.ObjectStorageBucketName != nil {
		in, out := &in.ObjectStorageBucketName, &out.ObjectStorageBucketName
		*out = new(string)
		**out = **in
	}
	if in.ObjectStorageNamespace != nil {
		in, out := &in.ObjectStorageNamespace, &out.ObjectStorageNamespace
		*out = new(string)
		**out = **in
	}
	if in.ObjectStorageObjectNameFormat != nil {
		in, out := &in.ObjectStorageObjectNameFormat, &out.ObjectStorageObjectNameFormat
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStorageConfigInitParameters.
func (in *ObjectStorageConfigInitParameters) DeepCopy() *ObjectStorageConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageConfigObservation) DeepCopyInto(out *ObjectStorageConfigObservation) {
	*out = *in
	if in.ObjectStorageBucketName != nil {
		in, out := &in.ObjectStorageBucketName, &out.ObjectStorageBucketName
		*out = new(string)
		**out = **in
	}
	if in.ObjectStorageNamespace != nil {
		in, out := &in.ObjectStorageNamespace, &out.ObjectStorageNamespace
		*out = new(string)
		**out = **in
	}
	if in.ObjectStorageObjectNameFormat != nil {
		in, out := &in.ObjectStorageObjectNameFormat, &out.ObjectStorageObjectNameFormat
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStorageConfigObservation.
func (in *ObjectStorageConfigObservation) DeepCopy() *ObjectStorageConfigObservation {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageConfigParameters) DeepCopyInto(out *ObjectStorageConfigParameters) {
	*out = *in
	if in.ObjectStorageBucketName != nil {
		in, out := &in.ObjectStorageBucketName, &out.ObjectStorageBucketName
		*out = new(string)
		**out = **in
	}
	if in.ObjectStorageNamespace != nil {
		in, out := &in.ObjectStorageNamespace, &out.ObjectStorageNamespace
		*out = new(string)
		**out = **in
	}
	if in.ObjectStorageObjectNameFormat != nil {
		in, out := &in.ObjectStorageObjectNameFormat, &out.ObjectStorageObjectNameFormat
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStorageConfigParameters.
func (in *ObjectStorageConfigParameters) DeepCopy() *ObjectStorageConfigParameters {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RevocationStatusInitParameters) DeepCopyInto(out *RevocationStatusInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RevocationStatusInitParameters.
func (in *RevocationStatusInitParameters) DeepCopy() *RevocationStatusInitParameters {
	if in == nil {
		return nil
	}
	out := new(RevocationStatusInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RevocationStatusObservation) DeepCopyInto(out *RevocationStatusObservation) {
	*out = *in
	if in.RevocationReason != nil {
		in, out := &in.RevocationReason, &out.RevocationReason
		*out = new(string)
		**out = **in
	}
	if in.TimeOfRevocation != nil {
		in, out := &in.TimeOfRevocation, &out.TimeOfRevocation
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RevocationStatusObservation.
func (in *RevocationStatusObservation) DeepCopy() *RevocationStatusObservation {
	if in == nil {
		return nil
	}
	out := new(RevocationStatusObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RevocationStatusParameters) DeepCopyInto(out *RevocationStatusParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RevocationStatusParameters.
func (in *RevocationStatusParameters) DeepCopy() *RevocationStatusParameters {
	if in == nil {
		return nil
	}
	out := new(RevocationStatusParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubjectInitParameters) DeepCopyInto(out *SubjectInitParameters) {
	*out = *in
	if in.CommonName != nil {
		in, out := &in.CommonName, &out.CommonName
		*out = new(string)
		**out = **in
	}
	if in.Country != nil {
		in, out := &in.Country, &out.Country
		*out = new(string)
		**out = **in
	}
	if in.DistinguishedNameQualifier != nil {
		in, out := &in.DistinguishedNameQualifier, &out.DistinguishedNameQualifier
		*out = new(string)
		**out = **in
	}
	if in.DomainComponent != nil {
		in, out := &in.DomainComponent, &out.DomainComponent
		*out = new(string)
		**out = **in
	}
	if in.GenerationQualifier != nil {
		in, out := &in.GenerationQualifier, &out.GenerationQualifier
		*out = new(string)
		**out = **in
	}
	if in.GivenName != nil {
		in, out := &in.GivenName, &out.GivenName
		*out = new(string)
		**out = **in
	}
	if in.Initials != nil {
		in, out := &in.Initials, &out.Initials
		*out = new(string)
		**out = **in
	}
	if in.LocalityName != nil {
		in, out := &in.LocalityName, &out.LocalityName
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.OrganizationalUnit != nil {
		in, out := &in.OrganizationalUnit, &out.OrganizationalUnit
		*out = new(string)
		**out = **in
	}
	if in.Pseudonym != nil {
		in, out := &in.Pseudonym, &out.Pseudonym
		*out = new(string)
		**out = **in
	}
	if in.SerialNumber != nil {
		in, out := &in.SerialNumber, &out.SerialNumber
		*out = new(string)
		**out = **in
	}
	if in.StateOrProvinceName != nil {
		in, out := &in.StateOrProvinceName, &out.StateOrProvinceName
		*out = new(string)
		**out = **in
	}
	if in.Street != nil {
		in, out := &in.Street, &out.Street
		*out = new(string)
		**out = **in
	}
	if in.Surname != nil {
		in, out := &in.Surname, &out.Surname
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubjectInitParameters.
func (in *SubjectInitParameters) DeepCopy() *SubjectInitParameters {
	if in == nil {
		return nil
	}
	out := new(SubjectInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubjectObservation) DeepCopyInto(out *SubjectObservation) {
	*out = *in
	if in.CommonName != nil {
		in, out := &in.CommonName, &out.CommonName
		*out = new(string)
		**out = **in
	}
	if in.Country != nil {
		in, out := &in.Country, &out.Country
		*out = new(string)
		**out = **in
	}
	if in.DistinguishedNameQualifier != nil {
		in, out := &in.DistinguishedNameQualifier, &out.DistinguishedNameQualifier
		*out = new(string)
		**out = **in
	}
	if in.DomainComponent != nil {
		in, out := &in.DomainComponent, &out.DomainComponent
		*out = new(string)
		**out = **in
	}
	if in.GenerationQualifier != nil {
		in, out := &in.GenerationQualifier, &out.GenerationQualifier
		*out = new(string)
		**out = **in
	}
	if in.GivenName != nil {
		in, out := &in.GivenName, &out.GivenName
		*out = new(string)
		**out = **in
	}
	if in.Initials != nil {
		in, out := &in.Initials, &out.Initials
		*out = new(string)
		**out = **in
	}
	if in.LocalityName != nil {
		in, out := &in.LocalityName, &out.LocalityName
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.OrganizationalUnit != nil {
		in, out := &in.OrganizationalUnit, &out.OrganizationalUnit
		*out = new(string)
		**out = **in
	}
	if in.Pseudonym != nil {
		in, out := &in.Pseudonym, &out.Pseudonym
		*out = new(string)
		**out = **in
	}
	if in.SerialNumber != nil {
		in, out := &in.SerialNumber, &out.SerialNumber
		*out = new(string)
		**out = **in
	}
	if in.StateOrProvinceName != nil {
		in, out := &in.StateOrProvinceName, &out.StateOrProvinceName
		*out = new(string)
		**out = **in
	}
	if in.Street != nil {
		in, out := &in.Street, &out.Street
		*out = new(string)
		**out = **in
	}
	if in.Surname != nil {
		in, out := &in.Surname, &out.Surname
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubjectObservation.
func (in *SubjectObservation) DeepCopy() *SubjectObservation {
	if in == nil {
		return nil
	}
	out := new(SubjectObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubjectParameters) DeepCopyInto(out *SubjectParameters) {
	*out = *in
	if in.CommonName != nil {
		in, out := &in.CommonName, &out.CommonName
		*out = new(string)
		**out = **in
	}
	if in.Country != nil {
		in, out := &in.Country, &out.Country
		*out = new(string)
		**out = **in
	}
	if in.DistinguishedNameQualifier != nil {
		in, out := &in.DistinguishedNameQualifier, &out.DistinguishedNameQualifier
		*out = new(string)
		**out = **in
	}
	if in.DomainComponent != nil {
		in, out := &in.DomainComponent, &out.DomainComponent
		*out = new(string)
		**out = **in
	}
	if in.GenerationQualifier != nil {
		in, out := &in.GenerationQualifier, &out.GenerationQualifier
		*out = new(string)
		**out = **in
	}
	if in.GivenName != nil {
		in, out := &in.GivenName, &out.GivenName
		*out = new(string)
		**out = **in
	}
	if in.Initials != nil {
		in, out := &in.Initials, &out.Initials
		*out = new(string)
		**out = **in
	}
	if in.LocalityName != nil {
		in, out := &in.LocalityName, &out.LocalityName
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.OrganizationalUnit != nil {
		in, out := &in.OrganizationalUnit, &out.OrganizationalUnit
		*out = new(string)
		**out = **in
	}
	if in.Pseudonym != nil {
		in, out := &in.Pseudonym, &out.Pseudonym
		*out = new(string)
		**out = **in
	}
	if in.SerialNumber != nil {
		in, out := &in.SerialNumber, &out.SerialNumber
		*out = new(string)
		**out = **in
	}
	if in.StateOrProvinceName != nil {
		in, out := &in.StateOrProvinceName, &out.StateOrProvinceName
		*out = new(string)
		**out = **in
	}
	if in.Street != nil {
		in, out := &in.Street, &out.Street
		*out = new(string)
		**out = **in
	}
	if in.Surname != nil {
		in, out := &in.Surname, &out.Surname
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubjectParameters.
func (in *SubjectParameters) DeepCopy() *SubjectParameters {
	if in == nil {
		return nil
	}
	out := new(SubjectParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidityInitParameters) DeepCopyInto(out *ValidityInitParameters) {
	*out = *in
	if in.TimeOfValidityNotAfter != nil {
		in, out := &in.TimeOfValidityNotAfter, &out.TimeOfValidityNotAfter
		*out = new(string)
		**out = **in
	}
	if in.TimeOfValidityNotBefore != nil {
		in, out := &in.TimeOfValidityNotBefore, &out.TimeOfValidityNotBefore
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidityInitParameters.
func (in *ValidityInitParameters) DeepCopy() *ValidityInitParameters {
	if in == nil {
		return nil
	}
	out := new(ValidityInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidityObservation) DeepCopyInto(out *ValidityObservation) {
	*out = *in
	if in.TimeOfValidityNotAfter != nil {
		in, out := &in.TimeOfValidityNotAfter, &out.TimeOfValidityNotAfter
		*out = new(string)
		**out = **in
	}
	if in.TimeOfValidityNotBefore != nil {
		in, out := &in.TimeOfValidityNotBefore, &out.TimeOfValidityNotBefore
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidityObservation.
func (in *ValidityObservation) DeepCopy() *ValidityObservation {
	if in == nil {
		return nil
	}
	out := new(ValidityObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidityParameters) DeepCopyInto(out *ValidityParameters) {
	*out = *in
	if in.TimeOfValidityNotAfter != nil {
		in, out := &in.TimeOfValidityNotAfter, &out.TimeOfValidityNotAfter
		*out = new(string)
		**out = **in
	}
	if in.TimeOfValidityNotBefore != nil {
		in, out := &in.TimeOfValidityNotBefore, &out.TimeOfValidityNotBefore
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidityParameters.
func (in *ValidityParameters) DeepCopy() *ValidityParameters {
	if in == nil {
		return nil
	}
	out := new(ValidityParameters)
	in.DeepCopyInto(out)
	return out
}
