apiVersion: file.rockchico.dev/v1alpha1
kind: StorageExportSet
metadata:
  annotations:
    meta.upbound.io/example-id: file/v1alpha1/storageexportset
  labels:
    testing.upbound.io/example-name: test_export_set
  name: test-export-set
spec:
  forProvider:
    displayName: ${var.export_set_name}
    maxFsStatBytes: 23843202333
    maxFsStatFiles: 223442
    mountTargetId: ${oci_file_storage_mount_target.test_mount_target.id}
