apiVersion: file.rockchico.dev/v1alpha1
kind: StorageReplication
metadata:
  annotations:
    meta.upbound.io/example-id: file/v1alpha1/storagereplication
  labels:
    testing.upbound.io/example-name: test_replication
  name: test-replication
spec:
  forProvider:
    compartmentId: ${var.compartment_id}
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.replication_display_name}
    freeformTags:
      Department: Finance
    replicationInterval: ${var.replication_replication_interval}
    sourceId: ${oci_file_storage_file_system.test_source.id}
    targetId: ${oci_file_storage_file_system.test_target.id}
