apiVersion: artifacts.rockchico.dev/v1alpha1
kind: ContainerRepository
metadata:
  annotations:
    meta.upbound.io/example-id: artifacts/v1alpha1/containerrepository
  labels:
    testing.upbound.io/example-name: test_container_repository
  name: test-container-repository
spec:
  forProvider:
    compartmentId: ${var.compartment_id}
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.container_repository_display_name}
    freeformTags:
      Department: Finance
    isImmutable: ${var.container_repository_is_immutable}
    isPublic: ${var.container_repository_is_public}
    readme:
    - content: ${var.container_repository_readme_content}
      format: ${var.container_repository_readme_format}
