apiVersion: core.rockchico.dev/v1alpha1
kind: DrgAttachmentsList
metadata:
  annotations:
    meta.upbound.io/example-id: core/v1alpha1/drgattachmentslist
  labels:
    testing.upbound.io/example-name: test_drg_attachments_list
  name: test-drg-attachments-list
spec:
  forProvider:
    attachmentType: ${var.drg_attachments_list_attachment_type}
    drgId: ${oci_core_drg.test_drg.id}
    isCrossTenancy: ${var.drg_attachments_list_is_cross_tenancy}
