apiVersion: core.rockchico.dev/v1alpha1
kind: DrgAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: core/v1alpha1/drgattachment
  labels:
    testing.upbound.io/example-name: test_drg_attachment
  name: test-drg-attachment
spec:
  forProvider:
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.drg_attachment_display_name}
    drgId: ${oci_core_drg.test_drg.id}
    drgRouteTableId: ${oci_core_drg_route_table.test_drg_route_table.id}
    freeformTags:
      Department: Finance
    networkDetails:
    - id: ${oci_core_vcn.test_vcn.id}
      routeTableId: ${oci_core_route_table.test_route_table.id}
      type: ${var.drg_attachment_network_details_type}
      vcnRouteType: ${var.drg_attachment_network_details_vcn_route_type}
