apiVersion: core.rockchico.dev/v1alpha1
kind: DrgRouteDistribution
metadata:
  annotations:
    meta.upbound.io/example-id: core/v1alpha1/drgroutedistribution
  labels:
    testing.upbound.io/example-name: test_drg_route_distribution
  name: test-drg-route-distribution
spec:
  forProvider:
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.drg_route_distribution_display_name}
    distributionType: ${var.drg_route_distribution_distribution_type}
    drgId: ${oci_core_drg.test_drg.id}
    freeformTags:
      Department: Finance
