apiVersion: core.rockchico.dev/v1alpha1
kind: LocalPeeringGateway
metadata:
  annotations:
    meta.upbound.io/example-id: core/v1alpha1/localpeeringgateway
  labels:
    testing.upbound.io/example-name: test_local_peering_gateway
  name: test-local-peering-gateway
spec:
  forProvider:
    compartmentId: ${var.compartment_id}
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.local_peering_gateway_display_name}
    freeformTags:
      Department: Finance
    peerId: ${oci_core_local_peering_gateway.test_local_peering_gateway2.id}
    routeTableId: ${oci_core_route_table.test_route_table.id}
    vcnId: ${oci_core_vcn.test_vcn.id}
