apiVersion: core.rockchico.dev/v1alpha1
kind: NetworkSecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: core/v1alpha1/networksecuritygroup
  labels:
    testing.upbound.io/example-name: test_network_security_group
  name: test-network-security-group
spec:
  forProvider:
    compartmentId: ${var.compartment_id}
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.network_security_group_display_name}
    freeformTags:
      Department: Finance
    vcnId: ${oci_core_vcn.test_vcn.id}
