apiVersion: core.rockchico.dev/v1alpha1
kind: ServiceGateway
metadata:
  annotations:
    meta.upbound.io/example-id: core/v1alpha1/servicegateway
  labels:
    testing.upbound.io/example-name: test_service_gateway
  name: test-service-gateway
spec:
  forProvider:
    compartmentId: ${var.compartment_id}
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.service_gateway_display_name}
    freeformTags:
      Department: Finance
    routeTableId: ${oci_core_route_table.test_route_table.id}
    services:
    - serviceId: ${data.oci_core_services.test_services.services.0.id}
    vcnId: ${oci_core_vcn.test_vcn.id}
