apiVersion: core.rockchico.dev/v1alpha1
kind: Vlan
metadata:
  annotations:
    meta.upbound.io/example-id: core/v1alpha1/vlan
  labels:
    testing.upbound.io/example-name: test_vlan
  name: test-vlan
spec:
  forProvider:
    availabilityDomain: ${var.vlan_availability_domain}
    cidrBlock: ${var.vlan_cidr_block}
    compartmentId: ${var.compartment_id}
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.vlan_display_name}
    freeformTags:
      Department: Finance
    nsgIds: ${var.vlan_nsg_ids}
    routeTableId: ${oci_core_route_table.test_route_table.id}
    vcnId: ${oci_core_vcn.test_vcn.id}
    vlanTag: ${var.vlan_vlan_tag}
