apiVersion: core.rockchico.dev/v1alpha1
kind: VolumeBackupPolicyAssignment
metadata:
  annotations:
    meta.upbound.io/example-id: core/v1alpha1/volumebackuppolicyassignment
  labels:
    testing.upbound.io/example-name: test_volume_backup_policy_assignment
  name: test-volume-backup-policy-assignment
spec:
  forProvider:
    assetId: ${oci_core_volume.test_volume.id}
    policyId: ${oci_core_volume_backup_policy.test_volume_backup_policy.id}
