apiVersion: dns.rockchico.dev/v1alpha1
kind: SteeringPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1alpha1/steeringpolicy
  labels:
    testing.upbound.io/example-name: test_steering_policy
  name: test-steering-policy
spec:
  forProvider:
    answers:
    - isDisabled: ${var.steering_policy_answers_is_disabled}
      name: ${var.steering_policy_answers_name}
      pool: ${var.steering_policy_answers_pool}
      rdata: ${var.steering_policy_answers_rdata}
      rtype: ${var.steering_policy_answers_rtype}
    compartmentId: ${var.compartment_id}
    definedTags: ${var.steering_policy_defined_tags}
    displayName: ${var.steering_policy_display_name}
    freeformTags: ${var.steering_policy_freeform_tags}
    healthCheckMonitorId: ${oci_health_checks_http_monitor.test_http_monitor.id}
    rules:
    - cases:
      - answerData:
        - answerCondition: ${var.steering_policy_rules_cases_answer_data_answer_condition}
          shouldKeep: ${var.steering_policy_rules_cases_answer_data_should_keep}
          value: ${var.steering_policy_rules_cases_answer_data_value}
        caseCondition: ${var.steering_policy_rules_cases_case_condition}
        count: ${var.steering_policy_rules_cases_count}
      defaultAnswerData:
      - answerCondition: ${var.steering_policy_rules_default_answer_data_answer_condition}
        shouldKeep: ${var.steering_policy_rules_default_answer_data_should_keep}
        value: ${var.steering_policy_rules_default_answer_data_value}
      defaultCount: ${var.steering_policy_rules_default_count}
      description: ${var.steering_policy_rules_description}
      ruleType: ${var.steering_policy_rules_rule_type}
    template: ${var.steering_policy_template}
    ttl: ${var.steering_policy_ttl}
