// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type BalancerSSLCipherSuiteInitParameters struct {
	Ciphers []*string `json:"ciphers,omitempty" tf:"ciphers,omitempty"`

	// The OCID of the associated load balancer.
	LoadBalancerID *string `json:"loadBalancerId,omitempty" tf:"load_balancer_id,omitempty"`

	// A friendly name for the SSL cipher suite. It must be unique and it cannot be changed.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type BalancerSSLCipherSuiteObservation struct {
	Ciphers []*string `json:"ciphers,omitempty" tf:"ciphers,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The OCID of the associated load balancer.
	LoadBalancerID *string `json:"loadBalancerId,omitempty" tf:"load_balancer_id,omitempty"`

	// A friendly name for the SSL cipher suite. It must be unique and it cannot be changed.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type BalancerSSLCipherSuiteParameters struct {

	// +kubebuilder:validation:Optional
	Ciphers []*string `json:"ciphers,omitempty" tf:"ciphers,omitempty"`

	// The OCID of the associated load balancer.
	// +kubebuilder:validation:Optional
	LoadBalancerID *string `json:"loadBalancerId,omitempty" tf:"load_balancer_id,omitempty"`

	// A friendly name for the SSL cipher suite. It must be unique and it cannot be changed.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// BalancerSSLCipherSuiteSpec defines the desired state of BalancerSSLCipherSuite
type BalancerSSLCipherSuiteSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     BalancerSSLCipherSuiteParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BalancerSSLCipherSuiteInitParameters `json:"initProvider,omitempty"`
}

// BalancerSSLCipherSuiteStatus defines the observed state of BalancerSSLCipherSuite.
type BalancerSSLCipherSuiteStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BalancerSSLCipherSuiteObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// BalancerSSLCipherSuite is the Schema for the BalancerSSLCipherSuites API. Provides the Ssl Cipher Suite resource in Oracle Cloud Infrastructure Load Balancer service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,provider-oci}
type BalancerSSLCipherSuite struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ciphers) || (has(self.initProvider) && has(self.initProvider.ciphers))",message="spec.forProvider.ciphers is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.loadBalancerId) || (has(self.initProvider) && has(self.initProvider.loadBalancerId))",message="spec.forProvider.loadBalancerId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   BalancerSSLCipherSuiteSpec   `json:"spec"`
	Status BalancerSSLCipherSuiteStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BalancerSSLCipherSuiteList contains a list of BalancerSSLCipherSuites
type BalancerSSLCipherSuiteList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BalancerSSLCipherSuite `json:"items"`
}

// Repository type metadata.
var (
	BalancerSSLCipherSuite_Kind             = "BalancerSSLCipherSuite"
	BalancerSSLCipherSuite_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BalancerSSLCipherSuite_Kind}.String()
	BalancerSSLCipherSuite_KindAPIVersion   = BalancerSSLCipherSuite_Kind + "." + CRDGroupVersion.String()
	BalancerSSLCipherSuite_GroupVersionKind = CRDGroupVersion.WithKind(BalancerSSLCipherSuite_Kind)
)

func init() {
	SchemeBuilder.Register(&BalancerSSLCipherSuite{}, &BalancerSSLCipherSuiteList{})
}
