// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type BalancerPathRouteSetInitParameters struct {

	// The OCID of the load balancer to add the path route set to.
	LoadBalancerID *string `json:"loadBalancerId,omitempty" tf:"load_balancer_id,omitempty"`

	// The name for this set of path route rules. It must be unique and it cannot be changed. Avoid entering confidential information.  Example: example_path_route_set
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Updatable) The set of path route rules.
	PathRoutes []PathRoutesInitParameters `json:"pathRoutes,omitempty" tf:"path_routes,omitempty"`
}

type BalancerPathRouteSetObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The OCID of the load balancer to add the path route set to.
	LoadBalancerID *string `json:"loadBalancerId,omitempty" tf:"load_balancer_id,omitempty"`

	// The name for this set of path route rules. It must be unique and it cannot be changed. Avoid entering confidential information.  Example: example_path_route_set
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Updatable) The set of path route rules.
	PathRoutes []PathRoutesObservation `json:"pathRoutes,omitempty" tf:"path_routes,omitempty"`

	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type BalancerPathRouteSetParameters struct {

	// The OCID of the load balancer to add the path route set to.
	// +kubebuilder:validation:Optional
	LoadBalancerID *string `json:"loadBalancerId,omitempty" tf:"load_balancer_id,omitempty"`

	// The name for this set of path route rules. It must be unique and it cannot be changed. Avoid entering confidential information.  Example: example_path_route_set
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Updatable) The set of path route rules.
	// +kubebuilder:validation:Optional
	PathRoutes []PathRoutesParameters `json:"pathRoutes,omitempty" tf:"path_routes,omitempty"`
}

type PathMatchTypeInitParameters struct {

	// (Updatable) Specifies how the load balancing service compares a PathRoute object's path string against the incoming URI.
	MatchType *string `json:"matchType,omitempty" tf:"match_type,omitempty"`
}

type PathMatchTypeObservation struct {

	// (Updatable) Specifies how the load balancing service compares a PathRoute object's path string against the incoming URI.
	MatchType *string `json:"matchType,omitempty" tf:"match_type,omitempty"`
}

type PathMatchTypeParameters struct {

	// (Updatable) Specifies how the load balancing service compares a PathRoute object's path string against the incoming URI.
	// +kubebuilder:validation:Optional
	MatchType *string `json:"matchType" tf:"match_type,omitempty"`
}

type PathRoutesInitParameters struct {

	// (Updatable) The name of the target backend set for requests where the incoming URI matches the specified path.  Example: example_backend_set
	BackendSetName *string `json:"backendSetName,omitempty" tf:"backend_set_name,omitempty"`

	// (Updatable) The path string to match against the incoming URI path.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// (Updatable) The type of matching to apply to incoming URIs.
	PathMatchType []PathMatchTypeInitParameters `json:"pathMatchType,omitempty" tf:"path_match_type,omitempty"`
}

type PathRoutesObservation struct {

	// (Updatable) The name of the target backend set for requests where the incoming URI matches the specified path.  Example: example_backend_set
	BackendSetName *string `json:"backendSetName,omitempty" tf:"backend_set_name,omitempty"`

	// (Updatable) The path string to match against the incoming URI path.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// (Updatable) The type of matching to apply to incoming URIs.
	PathMatchType []PathMatchTypeObservation `json:"pathMatchType,omitempty" tf:"path_match_type,omitempty"`
}

type PathRoutesParameters struct {

	// (Updatable) The name of the target backend set for requests where the incoming URI matches the specified path.  Example: example_backend_set
	// +kubebuilder:validation:Optional
	BackendSetName *string `json:"backendSetName" tf:"backend_set_name,omitempty"`

	// (Updatable) The path string to match against the incoming URI path.
	// +kubebuilder:validation:Optional
	Path *string `json:"path" tf:"path,omitempty"`

	// (Updatable) The type of matching to apply to incoming URIs.
	// +kubebuilder:validation:Optional
	PathMatchType []PathMatchTypeParameters `json:"pathMatchType" tf:"path_match_type,omitempty"`
}

// BalancerPathRouteSetSpec defines the desired state of BalancerPathRouteSet
type BalancerPathRouteSetSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     BalancerPathRouteSetParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BalancerPathRouteSetInitParameters `json:"initProvider,omitempty"`
}

// BalancerPathRouteSetStatus defines the observed state of BalancerPathRouteSet.
type BalancerPathRouteSetStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BalancerPathRouteSetObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// BalancerPathRouteSet is the Schema for the BalancerPathRouteSets API. Provides the Path Route Set resource in Oracle Cloud Infrastructure Load Balancer service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,provider-oci}
type BalancerPathRouteSet struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.loadBalancerId) || (has(self.initProvider) && has(self.initProvider.loadBalancerId))",message="spec.forProvider.loadBalancerId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.pathRoutes) || (has(self.initProvider) && has(self.initProvider.pathRoutes))",message="spec.forProvider.pathRoutes is a required parameter"
	Spec   BalancerPathRouteSetSpec   `json:"spec"`
	Status BalancerPathRouteSetStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BalancerPathRouteSetList contains a list of BalancerPathRouteSets
type BalancerPathRouteSetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BalancerPathRouteSet `json:"items"`
}

// Repository type metadata.
var (
	BalancerPathRouteSet_Kind             = "BalancerPathRouteSet"
	BalancerPathRouteSet_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BalancerPathRouteSet_Kind}.String()
	BalancerPathRouteSet_KindAPIVersion   = BalancerPathRouteSet_Kind + "." + CRDGroupVersion.String()
	BalancerPathRouteSet_GroupVersionKind = CRDGroupVersion.WithKind(BalancerPathRouteSet_Kind)
)

func init() {
	SchemeBuilder.Register(&BalancerPathRouteSet{}, &BalancerPathRouteSetList{})
}
