// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type BalancerHostnameInitParameters struct {

	// (Updatable) A virtual hostname. For more information about virtual hostname string construction, see Managing Request Routing.  Example: app.example.com
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// The OCID of the load balancer to add the hostname to.
	LoadBalancerID *string `json:"loadBalancerId,omitempty" tf:"load_balancer_id,omitempty"`

	// A friendly name for the hostname resource. It must be unique and it cannot be changed. Avoid entering confidential information.  Example: example_hostname_001
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type BalancerHostnameObservation struct {

	// (Updatable) A virtual hostname. For more information about virtual hostname string construction, see Managing Request Routing.  Example: app.example.com
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The OCID of the load balancer to add the hostname to.
	LoadBalancerID *string `json:"loadBalancerId,omitempty" tf:"load_balancer_id,omitempty"`

	// A friendly name for the hostname resource. It must be unique and it cannot be changed. Avoid entering confidential information.  Example: example_hostname_001
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type BalancerHostnameParameters struct {

	// (Updatable) A virtual hostname. For more information about virtual hostname string construction, see Managing Request Routing.  Example: app.example.com
	// +kubebuilder:validation:Optional
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// The OCID of the load balancer to add the hostname to.
	// +kubebuilder:validation:Optional
	LoadBalancerID *string `json:"loadBalancerId,omitempty" tf:"load_balancer_id,omitempty"`

	// A friendly name for the hostname resource. It must be unique and it cannot be changed. Avoid entering confidential information.  Example: example_hostname_001
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// BalancerHostnameSpec defines the desired state of BalancerHostname
type BalancerHostnameSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     BalancerHostnameParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BalancerHostnameInitParameters `json:"initProvider,omitempty"`
}

// BalancerHostnameStatus defines the observed state of BalancerHostname.
type BalancerHostnameStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BalancerHostnameObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// BalancerHostname is the Schema for the BalancerHostnames API. Provides the Hostname resource in Oracle Cloud Infrastructure Load Balancer service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,provider-oci}
type BalancerHostname struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.hostname) || (has(self.initProvider) && has(self.initProvider.hostname))",message="spec.forProvider.hostname is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.loadBalancerId) || (has(self.initProvider) && has(self.initProvider.loadBalancerId))",message="spec.forProvider.loadBalancerId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   BalancerHostnameSpec   `json:"spec"`
	Status BalancerHostnameStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BalancerHostnameList contains a list of BalancerHostnames
type BalancerHostnameList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BalancerHostname `json:"items"`
}

// Repository type metadata.
var (
	BalancerHostname_Kind             = "BalancerHostname"
	BalancerHostname_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BalancerHostname_Kind}.String()
	BalancerHostname_KindAPIVersion   = BalancerHostname_Kind + "." + CRDGroupVersion.String()
	BalancerHostname_GroupVersionKind = CRDGroupVersion.WithKind(BalancerHostname_Kind)
)

func init() {
	SchemeBuilder.Register(&BalancerHostname{}, &BalancerHostnameList{})
}
