// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *BalancerBackend) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BalancerBackendSet) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BalancerCertificate) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BalancerHostname) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BalancerListener) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BalancerLoadBalancer) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BalancerLoadBalancerRoutingPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BalancerPathRouteSet) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BalancerRuleSet) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BalancerSSLCipherSuite) Hub() {}
