apiVersion: network.rockchico.dev/v1alpha1
kind: LoadBalancerListener
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/loadbalancerlistener
  labels:
    testing.upbound.io/example-name: test_listener
  name: test-listener
spec:
  forProvider:
    defaultBackendSetName: ${var.backend_set_name}
    ipVersion: ${var.listener_ip_version}
    isPpv2Enabled: ${var.listener_is_ppv2enabled}
    name: ${var.listener_name}
    networkLoadBalancerId: ${oci_network_load_balancer_network_load_balancer.test_network_load_balancer.id}
    port: ${var.listener_port}
    protocol: ${var.listener_protocol}
    tcpIdleTimeout: ${var.listener_tcp_idle_timeout}
    udpIdleTimeout: ${var.listener_udp_idle_timeout}
