apiVersion: kms.rockchico.dev/v1alpha1
kind: KeyVersion
metadata:
  annotations:
    meta.upbound.io/example-id: kms/v1alpha1/keyversion
  labels:
    testing.upbound.io/example-name: test_key_version
  name: test-key-version
spec:
  forProvider:
    externalKeyVersionId: ${oci_kms_key_version.test_key_version.id}
    keyId: ${oci_kms_key.test_key.id}
    managementEndpoint: ${var.key_version_management_endpoint}
