apiVersion: vault.rockchico.dev/v1alpha1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: vault/v1alpha1/secret
  labels:
    testing.upbound.io/example-name: test_secret
  name: test-secret
spec:
  forProvider:
    compartmentId: ${var.compartment_id}
    definedTags:
      Operations.CostCenter: "42"
    description: ${var.secret_description}
    freeformTags:
      Department: Finance
    keyId: ${oci_kms_key.test_key.id}
    metadata: ${var.secret_metadata}
    rotationConfig:
    - isScheduledRotationEnabled: ${var.secret_rotation_config_is_scheduled_rotation_enabled}
      rotationInterval: ${var.secret_rotation_config_rotation_interval}
      targetSystemDetails:
      - adbId: ${oci_vault_adb.test_adb.id}
        functionId: ${oci_functions_function.test_function.id}
        targetSystemType: ${var.secret_rotation_config_target_system_details_target_system_type}
    secretContent:
    - content: ${var.secret_secret_content_content}
      contentType: ${var.secret_secret_content_content_type}
      name: ${var.secret_secret_content_name}
      stage: ${var.secret_secret_content_stage}
    - content: ${var.secret_secret_content_content}
      contentType: ${var.secret_secret_content_content_type}
      name: ${var.secret_secret_content_name}
      stage: ${var.secret_secret_content_stage}
    secretName: ${oci_vault_secret.test_secret.name}
    secretRules:
    - isEnforcedOnDeletedSecretVersions: ${var.secret_secret_rules_is_enforced_on_deleted_secret_versions}
      isSecretContentRetrievalBlockedOnExpiry: ${var.secret_secret_rules_is_secret_content_retrieval_blocked_on_expiry}
      ruleType: ${var.secret_secret_rules_rule_type}
      secretVersionExpiryInterval: ${var.secret_secret_rules_secret_version_expiry_interval}
      timeOfAbsoluteExpiry: ${var.secret_secret_rules_time_of_absolute_expiry}
    vaultId: ${oci_kms_vault.test_vault.id}
