apiVersion: health.rockchico.dev/v1alpha1
kind: ChecksHTTPMonitor
metadata:
  annotations:
    meta.upbound.io/example-id: health/v1alpha1/checkshttpmonitor
  labels:
    testing.upbound.io/example-name: test_http_monitor
  name: test-http-monitor
spec:
  forProvider:
    compartmentId: ${var.compartment_id}
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.http_monitor_display_name}
    freeformTags:
      Department: Finance
    headers: ${var.http_monitor_headers}
    intervalInSeconds: ${var.http_monitor_interval_in_seconds}
    isEnabled: ${var.http_monitor_is_enabled}
    method: ${var.http_monitor_method}
    path: ${var.http_monitor_path}
    port: ${var.http_monitor_port}
    protocol: ${var.http_monitor_protocol}
    targets: ${var.http_monitor_targets}
    timeoutInSeconds: ${var.http_monitor_timeout_in_seconds}
    vantagePointNames: ${var.http_monitor_vantage_point_names}
