apiVersion: ons.rockchico.dev/v1alpha1
kind: Subscription
metadata:
  annotations:
    meta.upbound.io/example-id: ons/v1alpha1/subscription
  labels:
    testing.upbound.io/example-name: test_subscription
  name: test-subscription
spec:
  forProvider:
    compartmentId: ${var.compartment_id}
    definedTags:
      Operations.CostCenter: "42"
    endpoint: ${var.subscription_endpoint}
    freeformTags:
      Department: Finance
    protocol: ${var.subscription_protocol}
    topicId: ${oci_ons_notification_topic.test_notification_topic.id}
