apiVersion: streaming.rockchico.dev/v1alpha1
kind: Stream
metadata:
  annotations:
    meta.upbound.io/example-id: streaming/v1alpha1/stream
  labels:
    testing.upbound.io/example-name: test_stream
  name: test-stream
spec:
  forProvider:
    compartmentId: ${var.compartment_id}
    definedTags: ${var.stream_defined_tags}
    freeformTags:
      Department: Finance
    name: ${var.stream_name}
    partitions: ${var.stream_partitions}
    retentionInHours: ${var.stream_retention_in_hours}
    streamPoolId: ${oci_streaming_stream_pool.test_stream_pool.id}
