apiVersion: events.rockchico.dev/v1alpha1
kind: Rule
metadata:
  annotations:
    meta.upbound.io/example-id: events/v1alpha1/rule
  labels:
    testing.upbound.io/example-name: test_rule
  name: test-rule
spec:
  forProvider:
    actions:
    - actions:
      - actionType: ${var.rule_actions_actions_action_type}
        description: ${var.rule_actions_actions_description}
        functionId: ${oci_functions_function.test_function.id}
        isEnabled: ${var.rule_actions_actions_is_enabled}
        streamId: ${oci_streaming_stream.test_stream.id}
        topicId: ${oci_ons_notification_topic.test_topic.id}
    compartmentId: ${var.compartment_id}
    condition: ${var.rule_condition}
    definedTags:
      Operations.CostCenter: "42"
    description: ${var.rule_description}
    displayName: ${var.rule_display_name}
    freeformTags:
      Department: Finance
    isEnabled: ${var.rule_is_enabled}
