// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *MeshAccessPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MeshIngressGateway) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MeshIngressGatewayRouteTable) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MeshMesh) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MeshVirtualDeployment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MeshVirtualService) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MeshVirtualServiceRouteTable) Hub() {}
