apiVersion: load.rockchico.dev/v1alpha1
kind: BalancerCertificate
metadata:
  annotations:
    meta.upbound.io/example-id: load/v1alpha1/balancercertificate
  labels:
    testing.upbound.io/example-name: test_certificate
  name: test-certificate
spec:
  forProvider:
    caCertificate: ${var.certificate_ca_certificate}
    certificateName: ${var.certificate_certificate_name}
    loadBalancerId: ${oci_load_balancer_load_balancer.test_load_balancer.id}
    passphraseSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    privateKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    publicCertificate: ${var.certificate_public_certificate}
