apiVersion: load.rockchico.dev/v1alpha1
kind: BalancerLoadBalancer
metadata:
  annotations:
    meta.upbound.io/example-id: load/v1alpha1/balancerloadbalancer
  labels:
    testing.upbound.io/example-name: test_load_balancer
  name: test-load-balancer
spec:
  forProvider:
    compartmentId: ${var.compartment_id}
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.load_balancer_display_name}
    freeformTags:
      Department: Finance
    ipMode: ${var.load_balancer_ip_mode}
    isDeleteProtectionEnabled: ${var.load_balancer_is_delete_protection_enabled}
    isPrivate: ${var.load_balancer_is_private}
    isRequestIdEnabled: ${var.load_balancer_is_request_id_enabled}
    networkSecurityGroupIds: ${var.load_balancer_network_security_group_ids}
    requestIdHeader: ${var.load_balancer_request_id_header}
    reservedIps:
    - id: ${var.load_balancer_reserved_ips_id}
    shape: ${var.load_balancer_shape}
    shapeDetails:
    - maximumBandwidthInMbps: ${var.load_balancer_shape_details_maximum_bandwidth_in_mbps}
      minimumBandwidthInMbps: ${var.load_balancer_shape_details_minimum_bandwidth_in_mbps}
    subnetIds: ${var.load_balancer_subnet_ids}
