apiVersion: service.rockchico.dev/v1alpha1
kind: MeshMesh
metadata:
  annotations:
    meta.upbound.io/example-id: service/v1alpha1/meshmesh
  labels:
    testing.upbound.io/example-name: test_mesh
  name: test-mesh
spec:
  forProvider:
    certificateAuthorities:
    - id: ${var.mesh_certificate_authorities_id}
    compartmentId: ${var.compartment_id}
    definedTags:
      foo-namespace.bar-key: value
    description: ${var.mesh_description}
    displayName: ${var.mesh_display_name}
    freeformTags:
      bar-key: value
    mtls:
    - minimum: ${var.mesh_mtls_minimum}
