apiVersion: service.rockchico.dev/v1alpha1
kind: MeshVirtualService
metadata:
  annotations:
    meta.upbound.io/example-id: service/v1alpha1/meshvirtualservice
  labels:
    testing.upbound.io/example-name: test_virtual_service
  name: test-virtual-service
spec:
  forProvider:
    compartmentId: ${var.compartment_id}
    defaultRoutingPolicy:
    - type: ${var.virtual_service_default_routing_policy_type}
    definedTags:
      foo-namespace.bar-key: value
    description: ${var.virtual_service_description}
    freeformTags:
      bar-key: value
    hosts: ${var.virtual_service_hosts}
    meshId: ${oci_service_mesh_mesh.test_mesh.id}
    mtls:
    - maximumValidity: ${var.virtual_service_mtls_maximum_validity}
      mode: ${var.virtual_service_mtls_mode}
    name: ${var.virtual_service_name}
