apiVersion: service.rockchico.dev/v1alpha1
kind: MeshAccessPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: service/v1alpha1/meshaccesspolicy
  labels:
    testing.upbound.io/example-name: test_access_policy
  name: test-access-policy
spec:
  forProvider:
    compartmentId: ${var.compartment_id}
    definedTags:
      foo-namespace.bar-key: value
    description: ${var.access_policy_description}
    freeformTags:
      bar-key: value
    meshId: ${oci_service_mesh_mesh.test_mesh.id}
    name: ${var.access_policy_name}
    rules:
    - action: ${var.access_policy_rules_action}
      destination:
      - hostnames: ${var.access_policy_rules_destination_hostnames}
        ingressGatewayId: ${oci_service_mesh_ingress_gateway.test_ingress_gateway.id}
        ipAddresses: ${var.access_policy_rules_destination_ip_addresses}
        ports: ${var.access_policy_rules_destination_ports}
        protocol: ${var.access_policy_rules_destination_protocol}
        type: ${var.access_policy_rules_destination_type}
        virtualServiceId: ${oci_service_mesh_virtual_service.test_virtual_service.id}
      source:
      - hostnames: ${var.access_policy_rules_source_hostnames}
        ingressGatewayId: ${oci_service_mesh_ingress_gateway.test_ingress_gateway.id}
        ipAddresses: ${var.access_policy_rules_source_ip_addresses}
        ports: ${var.access_policy_rules_source_ports}
        protocol: ${var.access_policy_rules_source_protocol}
        type: ${var.access_policy_rules_source_type}
        virtualServiceId: ${oci_service_mesh_virtual_service.test_virtual_service.id}
